[tool.ruff]
line-length = 160
target-version = "py311"

[tool.ruff.lint]
extend-select = ["E", "F", "I"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
check_untyped_defs = true
no_implicit_optional = true
strict_optional = true

